site_name:        Compose.jl
repo_url:         https://github.com/dcjones/Compose.jl
site_description: Declarative vector graphs
site_author:      dcjones

theme: readthedocs

docs_dir: 'build'

pages:
  - Home: index.md
